# Generated by Django 4.1.4 on 2023-01-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customgroup",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группы"},
        ),
    ]
