# Generated by Django 4.1.4 on 2023-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("group_auth", "0002_alter_customgroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="city",
            field=models.CharField(
                choices=[
                    ("SARAN", "Сарань"),
                    ("KAZ_BY", "Казыбек Би"),
                    ("BUKEY", "Букейханов"),
                    ("MAIKEN", "Майкудук"),
                    ("JBI", "ЖБИ"),
                    ("SHAHTINSK", "Шахтинск"),
                    ("ABAY", "Абай"),
                    ("TEMIRTAU", "Темиртау"),
                ],
                default="KAZ_BY",
                max_length=100,
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="groups",
            field=models.ManyToManyField(to="auth.group", verbose_name="Группа"),
        ),
    ]
